name: TFL CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - "**.go"
      - "go.**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go 1.21.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'
    - uses: Jerome1337/gofmt-action@v1.0.4
    # - name: Run linter
    #   run: make lint
    - name: Run unit tests
      run: go test ./lab1_0/trs/

